site_name: Starbot文档
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - 首页: index.md
  - 快速开始: first_bot.md
  - 编写插件: add_plugin.md